spring:
  application:
    name: eurekaServer
  security:
    basic:
      enable: true
    user:
      name: mseureka
      password: keseramu

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true