spring:
  application:
    name: eurekaServer
  security:
    basic:
      enabled: true
    user:
      name: brunno-user
      password: 123456789

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
